Repository ubcuas/ACOM, pull requests merged in 2022-12, with the labels that each got.

#1 Create dependabot.yml
  .github/dependabot.yml
Labels: Priority: High, Status: Review Needed, Type: CI/CD, Type: Dependency

#11 Update dependabot.yml
  .github/dependabot.yml
Labels: Priority: High, Status: Review Needed, Type: CI/CD, Type: Dependency

#12 Create codeql.yml
  .github/workflows/codeql.yml
Labels: Priority: Medium, Status: Review Needed, Type: Security

#13 Create dependency-review.yml
  .github/workflows/dependency-review.yml
Labels: Priority: Low, Status: Review Needed, Type: Security, Type: Dependency

#14 Fixed typo
  README.md
Labels: Priority: Low, Status: Review Needed, Type: Documentation

#20 Remove DS_Store
  .DS_Store
  .gitignore
Labels: Priority: Low, Status: Review Needed, Type: Cleaning / Optimization

#21 Update codeql.yml
  .github/workflows/codeql.yml
Labels: Priority: Low, Status: Review Needed, Type: Cleaning / Optimization
